### ISSUE TITLE
Laravel Valet on Fedora (Solved)

### ISSUE THREAD

**Issue by nickclasener** [cpriego/valet-linux#106]
problem 1 
After valet install run valet status if nginx and php-fpm are not running
Go To:

```
sudo vim /etc/selinux/config 
SELINUX=enforcing // change this 
// To:
SELINUX=permissive
```

problem 2
127.0.53.53 instead of 127.0.0.1
This has to do with TLD google dns more info on why [Here](https://iyware.com/dont-use-dev-for-development/)
The Solution is to `valet domain app // this changes .dev to .app`

```
PING example.dev (127.0.53.53) 56(84) bytes of data.
64 bytes from localhost (127.0.53.53): icmp_seq=1 ttl=64 time=0.021 ms
64 bytes from localhost (127.0.53.53): icmp_seq=2 ttl=64 time=0.070 ms
64 bytes from localhost (127.0.53.53): icmp_seq=3 ttl=64 time=0.072 ms

PING example.app (127.0.0.1) 56(84) bytes of data.
64 bytes from localhost (127.0.0.1): icmp_seq=1 ttl=64 time=0.021 ms
64 bytes from localhost (127.0.0.1): icmp_seq=2 ttl=64 time=0.070 ms
64 bytes from localhost (127.0.0.1): icmp_seq=3 ttl=64 time=0.072 ms

```

**Comment by TheNodi** [comment]
Problem 1

This is explained in the installation guide: https://cpriego.github.io/valet-linux/requirements#fedora

Problem 2

We have discussed the domain problem in issue #98 , to avoid this (and many other problems) the default TLD has been changed to `.test`. I suggest to use `.test` or `.local` instead of `.app` since it is a reserved TLD as well (See [wikipedia](https://en.wikipedia.org/wiki/.app_(gTLD)) ).
