### ISSUE TITLE
Valet share always redirects to 404

### ISSUE THREAD

**Issue by JapSeyz** [cpriego/valet-linux#128]
Local projects works fine, but sharing a site always leads to a 404

![34543533-a58444d0-f0e1-11e7-9da2-40c7a4781bb2](https://user-images.githubusercontent.com/2234034/34651126-37f7d858-f3cc-11e7-9f4d-9752e73a588b.png)

**Comment by JapSeyz** [comment]
`valet unsecure` and `valet port 80` doesn't fix it, btw.

**Comment by TheNodi** [comment]
Does it shows "Valet - 404 Not Found" page?

Can you try using all lower case domain letters? There's might be some issue there.

**Comment by JapSeyz** [comment]
Still receiving an error, albeit now it's a 301 error,
![screenshot from 2018-01-15 16 38 07](https://user-images.githubusercontent.com/2234034/34950133-8cdfd482-fa12-11e7-8d30-5d4a941998f0.png)

**Comment by TheNodi** [comment]
Where does it redirects you? 
Is it an application of some type or just static contents?

**Comment by JapSeyz** [comment]
It's a Laravel application.

It redirects to the same page. Google Chrome just stops it saying it redirected too many times.

I think it may be related to an SSL issue, as even if I unsecure this site, it keeps redirecting me to HTTPS if there's ANY other secured sites in a 'parked' directory

**Comment by TheNodi** [comment]
**BUG 1**: I can confirm your first bug, valet doesn't find uppercase domains. We are turning every directory into a slug to match it, this includes lowering every case (https://github.com/cpriego/valet-linux/blob/master/server.php#L105). This works well in every browser because they lowercase the domain before sending it (domains are case insensitive), but nginx (and ngrok) keeps the domain as-is, including the case of chars. This results in a 404 on uppercase domains, it can be verified using curl.

I'm still not able to reproduce your second issue.
Steps I tried:
- Fresh install on Ubuntu 16.04
- Create a folder `code` and park it
- Create `code/site` and secure it
- I can access `https://site.test`
- Create `code/festihval` and keep it unsecured
- I can acess `https://fetihval.test`
- Share it using `valet share`
- I can still access ngrok address

Can you try to unsecure all sites, re-run `valet install` and try it again?
It would be perfect if you can give me some steps to reproduce the issue from a fresh installation of valet.

**Comment by JapSeyz** [comment]
I am using ElementaryOS not Ubuntu, but it is based upon Ubuntu 16.04.

Unsecuring all sites and running install again did not help.

Even after running valet unsecure on every domain individually, it still redirects me to HTTPS with a valid certificate. I can't unsecure any sites, even though it gives me the correct "Your site will now serve traffic over HTTP"

**Comment by JapSeyz** [comment]
It seemed it was still using the uppercase certificate stored in the .valet/certificated folder, and in .valet/nginx folder.

However I can not stop it from redirecting http to https requests

**Comment by TheNodi** [comment]
There might have been some issues deleting those files. If those folders aren't empty, remove all files from there and reload/restart nginx daemon. 
The 301 redirect is done by nginx, which should be matching domains case-insensitive, while files are case sensitives, this might have mess things up. 

You might want to delete `.valet` folder directly and run `valet install`, it should rebuild nginx configurations and stop doing this redirect.

**Comment by JapSeyz** [comment]
@TheNodi That did the trick. Thanks tremendously!

**Comment by chinlung** [comment]
> Does it shows "Valet - 404 Not Found" page?
> 
> Can you try using all lower case domain letters? There's might be some issue there.

Yes, should use lower case domain



> Does it shows "Valet - 404 Not Found" page?
> 
> Can you try using all lower case domain letters? There's might be some issue there.
