### ISSUE TITLE
Difference between valet-linux and valet-wsl?

### ISSUE THREAD

**Issue by strarsis** [cpriego/valet-linux#137]
Is valet-linux more general, but works well on WSL, too? 
Is valet-wsl more optimized for Windows WSL environment? 
Will one project be deprecated in favour of the other?

**Comment by TheNodi** [comment]
We don't officially support WSL or anything related to Windows. It might work, I actually never tested it (because I don't have Windows 10 and I don't even know how WSL works network-wise), but nothing is granted. 

I briefly looked at the commit made to valet-wsl to make it run on WSL and I'm positive this version can not work on Windows. It's already complicated enough to support multiple Linux distributions, I don't think supporting Windows would be possible (or wise).

Consider them different projects with different aims.
