### ISSUE TITLE
Will valet2.0 have the flexibility to switch PHP versions?

### ISSUE THREAD

**Issue by Jinva** [cpriego/valet-linux#142]
Hello! I am learning laravel this framework, the official valet can only be used on mac, very grateful to find your open source project on github, thank you very much! There were some surprises in the process of using it. I installed php5.6 and php7.2 on ubuntu16.04LTS. I tried to uninstall one of the PHP versions, and then I could use the command "valet install". Switched version, but this is very inconvenient. Will valet-linux consider the issue of PHP version switch when developing? What should I do?

**Comment by TheNodi** [comment]
This goes beyond the scope of Valet, but it works with any version between 5.6 and 7.2. You can switch version in the middle and valet will keep working (you have to restart php-fpm). 
To directly answer your question, no, we will not add a build in feature to change php version, because it's way too distro-dependent. 

If you want an out-of-the-box solution, take a look at [Laravel Homestead](https://laravel.com/docs/5.6/homestead#multiple-php-versions), it's heavier but full of features.

If you want to do it manually, you can use the `update-alternatives` feature of Ubuntu. Install all the needed php versions (they are separate packages, like php5.6 vs php7.1), and switch between versions using:
```
sudo update-alternatives --set php /usr/bin/php5.6
```

You can read more here: https://tecadmin.net/switch-between-multiple-php-version-on-ubuntu/
Or see how homestead does it here: https://github.com/laravel/homestead/blob/master/resources/aliases#L29

**Comment by Jinva** [comment]
Thank you very much for your help, but when I switch php version to 5.6, then execute the command "valet install" and I get a syntax error.
`PHP Parse error: syntax error, unexpected '-' (T_OBJECT_OPERATOR) in /home/jinva/.config/composer/vendor/tightenco/collect/src/Collect/Support/Collection.php on line 155`

**Comment by TheNodi** [comment]
We are requiring `tightenco/collect` at version `~5.3`, which means every version from 5.3 to 6.0 (excluded, so < 6.0). Laravel (and that package as well) from version 5.5 requires PHP 7.0. Since you installed valet using php 7.0 you probably installed a version greater than (or equals to) 5.5, which breaks as soon as you switch to php 5.6. 

You have two options:
- Uninstall valet, switch to php 5.6 and install it again, composer will check your php version and install  `tightenco/collect` <= 5.4. Make sure to never run `composer global update` using php >=7.0, or it will update the dependencies to a greater version (and you'll see the error again).
- Require a lower version of the package to lock the dependencies in place (it might conflict with other packages, give it a try):
```
composer global require tightenco/collect:5.4.33
```

**Comment by Jinva** [comment]
thank you so much for your kind help !
