### ISSUE TITLE
Case sensitive project names

### ISSUE THREAD

**Issue by jhhazelaar** [cpriego/valet-linux#16]
When user folder with capital letters domain gets a 404 - not found.

If installed valet on an Ubuntu 16 machine with php 5.6. When using valet link in folder with capital letter got an 404 - not found error. When linking with project name with lower case name, it works.

Maybe creating symlinks always with lower case characters?

**Comment by TheNodi** [comment]
You are correct, valet is [comparing the domain](https://github.com/cpriego/valet-linux/blob/master/server.php#L67) in case-sensitive and this is technically wrong because domains are case insensitive (even though common browsers converts uppercase letters to lower case in domain name).

Instead of creating symlinks always with lower case characters I would change valet to make a case insensitive check of paths so that every lowercase-uppercase combination is valid.

**Comment by cpriego** [comment]
@TheNodi I worked up something. Please check it out. #19

**Comment by cpriego** [comment]
@jhhazelaar Linux, contrary to OSX or Windows is case sensitive, and while changing just the `link` command is easy it would be inconsistent with `park` and that is not a trivial thing to do. Lucky for everybody Valet is not meant to be used in production so we came up with a solution to the caps issue and a lot more. Please update to the latest release to use the new "slugged" urls.

**Comment by jhhazelaar** [comment]
Awesome guys, thanks! I'll update it later today
