### ISSUE TITLE
valet highjacks value of DOCUMENT_ROOT and SCRIPT_FILENAME

### ISSUE THREAD

**Issue by COLABORATI** [cpriego/valet-linux#163]
valet sets the global variables 
```$_SERVER['DOCUMENT_ROOT']``` and ```$_SERVER['SCRIPT_FILENAME']```
to values that might not be expected and that might lead to breaking scripts that rely on these variables.  In my current install the values of these variables contain the string ```$HOME/.valet/Sites``` what makes these values *FAKE-VARIABLES* - this is especially bad if some scripts rely on the values that usually should be found in these variables.

**Comment by TheNodi** [comment]
We have to updated those values because valets uses a global `server.php` as entrypoint for every site. It basically works as load balancer.

Those updates are update on a per-driver basis, to allow every driver to set an appropriate value for his application. For example, Cake2 sets the following information:
```php
        $_SERVER['DOCUMENT_ROOT'] = $sitePath . '/webroot';
        $_SERVER['SCRIPT_FILENAME'] = $sitePath . '/webroot/index.php';
        $_SERVER['SCRIPT_NAME'] = '/index.php';
        $_SERVER['PHP_SELF'] = '/index.php';
```
If we don't do it, the results would be:
```php
        $_SERVER['DOCUMENT_ROOT'] = '/path/to/composer/cpriego/valet-linux';
        $_SERVER['SCRIPT_FILENAME'] = '/path/to/composer/cpriego/valet-linux/server.php';
        $_SERVER['SCRIPT_NAME'] = '/server.php';
        $_SERVER['PHP_SELF'] = '/server.php';
```
Which doesn't make sense at all.

The reason why you're seeing `$HOME/.valet/Sites` path is because the sites are server from a symlinked directory, so that we can serve all of your parked directories from a single Nginx host file.
You should not rely on the absolute path of `DOCUMENT_ROOT`, instead use a relative calculation or `__DIR__`/`__FILE__` magical constants.

If you really need to rely on those variables, you can use a Valet Custom Driver and set that as expected: https://laravel.com/docs/5.6/valet#custom-valet-drivers

I think you should ask / discuss about the pro/cons of difference approaches in the main Valet repository: https://github.com/laravel/valet
