### ISSUE TITLE
Bug: valet-linux does not revert /etc/resolv.conf symlink

### ISSUE THREAD

**Issue by bcorcoran** [cpriego/valet-linux#285]
Ubuntu 20.04 but shouldn't make a difference, this seems like a very basic bug.

When you run `valet uninstall` the uninstaller script does not revert the symlink to /etc/resolv.conf -> /opt/valet-linux/resolv.conf

But you remove the valet resolv.conf. This leaves the DNS resolution with systemd-resolved in a broken state and is a major bug. You cannot just leave people's systems like this if they want to uninstall. I realize you give a warning about starting systemd-resolved manually but simply starting the service back up does not fix the issue here.

All you need to do is make sure the script does this (i'm not going thru the process of submitting a PR for something so minor):

```
sudo rm -f /etc/resolv.conf
cat /etc/resolv.conf.bak | sudo tee /etc/resolv.conf
```

This will at least put a "working" (read: default) config back in place. What you *should* do is back up the pre-existing resolv.conf on install and restore it upon uninstall.

**Comment by bcorcoran** [comment]
@jmarcher so was this fixed? Or you're just closing it?

**Comment by cahna** [comment]
With 0 open issues, it must be a trustworthy solution!

With respect, the uninstall script is garbage. You are left to clean-up your system by yourself. [Even the documented uninstall steps are incomplete](https://cpriego.github.io/valet-linux/#uninstalling)... 

- You must manually stop and disable the systemd unit `valet-dns` (installed by this script, but not uninstalled). Also you should probably remove `/etc/systemd/system/valet-dns.service` or `'/etc/init.d/valet-dns'` (uninstall doesn't do this)
- Installing and uninstalling this broke `systemd-hostnamed` on my Ubuntu 20.04 system. Don't forget to re-enable that.
- `~/.valet` is not removed
- If you did not have nginx and/or php-fpm installed before, you must uninstall it and disable the associated systemd unit (not a major complaint, but a warning would be nice)
- If you already had your own local DNS resolver (not dnsmasq) running... lol whoops, have fun with that...
- This is not a "fix"... this is "we're doing things my way and you're going to like it"
```php
/**
     * Fix systemd-resolved configuration.
     *
     * @return void
     */
    public function fixResolved()
    {
        // $resolved = $this->resolvedConfigPath;

        // $this->files->backup($resolved);
        // $this->files->putAsUser($resolved, $this->files->get(__DIR__.'/../stubs/resolved.conf'));

        $this->sm->disable('systemd-resolved');
        $this->sm->stop('systemd-resolved');
    }
```

```
Valet Linux is a Laravel development environment for Linux minimalists.
```

Why use proven configuration management tools that include support for multiple OSes and package managers when you could reinvent the wheel for a single purpose? As a minimalist, I will stick to containers and hostfile updates instead of this pollution.

**Comment by jmarcher** [comment]
This is an open source repo, you are free to do PRs if you think some parts of this system can be improved. Thanks in advance.
