### ISSUE TITLE
Bug: arch linux installing php8-fpm but actually php-fpm 

### ISSUE THREAD

**Issue by halimkun** [cpriego/valet-linux#350]
**Basic info**

| Distro (Name and version) | PHP Version | Valet version |
| ------------------------- | ----------- | ------------- |
| Ex: Arch Linux x86_64          | 8.0.12       | 2.2.29         |

- [ ] I've checked the issue queue and could not find anything similar to my bug.
- [x] I'm on the latest version of valet-linux (`valet --version`): `Valet v2.2.29`
- [x] I've run `valet fix` and `valet install` after updating and before submitting my issue/feature.

**What is the problem?**
when running valet install failed to install php8-fpm.
in my condition php-fpm using php8.

**What was supposed to happen?**
install php-fpm instead of php8-fpm.
because the package arch php8-fpm doesn't exist, there's php-fpm

**What actually happened?**
installing php8-fpm using arch but error

**How to reproduce this?**
when running valet install failed to install php8-fpm.
in my condition php-fpm using php8.

**What is the solution?**
install php-fpm instead of php8-fpm

**Sources**
`-

---

```bash
$ valet install  
[sudo] password for user: 
Nginx was already enabled
Stopping nginx...
[php8-fpm] is not installed, installing it now via Pacman... 🍻
error: target not found: php8-fpm

In Pacman.php line 74:
                                            
      Pacman was unable to install [php8-fpm].  
                                            
install [--ignore-selinux]

```

**Comment by TronFortyTwo** [comment]
I am in the same situation. Looking forward for a fix or a workaround.

**Comment by KasparRosin** [comment]
> I worked around this by using valet use default to switch to php 8 from php 7

Had a similar problem on ubuntu with version php@8.1. For some reason using default worked.

```zsh
# Fails
valet use php # valet use php@8.1
E: Unable to locate package phpphp-fpm
```

```zsh
# Succeeds
valet use default
Enabling php8.1-fpm...
```

**Comment by NAHDI51** [comment]
I might be a little late.

I did a workaround, which worked (at least it seems to work.)

1. Open the file: `$HOME/.config/composer/vendor/cpriego/valet-linux/cli/Valet/PhpFpm.php`. Simply said, this file installs the php-fpm dependency.

2. At line 46 or thereabouts, you'll find the `install` function. Check for the following block of code:
```
    if (!$this->pm->installed("php{$this->getPhpVersion()}-fpm")) {
            $this->pm->ensureInstalled("php{$this->getPhpVersion()}-fpm");
            $this->sm->enable($this->fpmServiceName());
        }
```
3. And remove the getPhpVersion() function, so that the title stands as 'php-fpm'.
```
    if (!$this->pm->installed("php-fpm")) {
            $this->pm->ensureInstalled("php-fpm");
            $this->sm->enable($this->fpmServiceName());
        }
```
4. At line 387 or thereabouts, you'll find a function named `fpmServiceName`. Check for the following block of code:
```
return "php{$version}-fpm";
```
5. And remove $version.
```
return "php-fpm";
```

This will replace php8-fpm with simply php-fpm, which exists in the AUR. The rest of the process will hopefully go smoothly.
