### ISSUE TITLE
Bug: `.test` domains cannot be resolved

### ISSUE THREAD

**Issue by codepuncher** [cpriego/valet-linux#387]
**Basic info**

| Distro (Name and version) | PHP Version | Valet version |
| ------------------------- | ----------- | ------------- |
| Ex: Manjaro 22.0.0        | 7.4.30      | 2.2.35 and [my fork (waiting on #369)](https://github.com/codepuncher/valet-linux/commit/3f49798d5ea7dccd3157c33fa712572a01a3b6a6) |

- [x] I've checked the issue queue and could not find anything similar to my bug.
- [x] I'm on the latest version of valet-linux (`valet --version`): `<Valet-Linux-Version>`
- [x] I've run `valet fix` and `valet install` after updating and before submitting my issue/feature. <--- fix is not a valid command!!!

**What is the problem?**
Viewing any .test domain is not recognised

**What was supposed to happen?**
To load the site

**What actually happened?**
connection refused

**How to reproduce this?**
I have no steps; just view .test site

**What is the solution?**
Temporary solution is to add entry to `/etc/hosts`

**Sources**
N/A

**Comment by ru44** [comment]
I had the same issue and I have stop apache and restart nginx

To troubleshoot the issue further, it may be helpful to check the valet logs (using the command valet logs) to see if there are any errors or warnings related to the .test domains. It may also be worth checking the Valet configuration file (~/.config/valet/config.json) to ensure that the .test TLD is included in the "tld" array.

If neither of these steps resolves the issue, it may be helpful to provide more information about the specific error message, any recent changes to the system or Valet configuration, and any other relevant details that could assist in identifying the root cause of the problem.

**Comment by Ferks-FK** [comment]
> **Basic info**
> 
> Distro (Name and version)	PHP Version	Valet version
> Ex: Manjaro 22.0.0	7.4.30	2.2.35 and [my fork (waiting on #369)](https://github.com/codepuncher/valet-linux/commit/3f49798d5ea7dccd3157c33fa712572a01a3b6a6)
> * [x]  I've checked the issue queue and could not find anything similar to my bug.
> * [x]  I'm on the latest version of valet-linux (`valet --version`): `<Valet-Linux-Version>`
> * [x]  I've run `valet fix` and `valet install` after updating and before submitting my issue/feature. <--- fix is not a valid command!!!
> 
> **What is the problem?** Viewing any .test domain is not recognised
> 
> **What was supposed to happen?** To load the site
> 
> **What actually happened?** connection refused
> 
> **How to reproduce this?** I have no steps; just view .test site
> 
> **What is the solution?** Temporary solution is to add entry to `/etc/hosts`
> 
> **Sources** N/A

Hi, I had the same problem in WSL2, my solution is basically to change the valet domain to `localhost` using `valet domain localhost`, this will make it so you don't always have to put a local domain in windows hosts for example.
