### ISSUE TITLE
Bug: Bad Gateway because valet.sock is not created

### ISSUE THREAD

**Issue by RafaelKr** [cpriego/valet-linux#413]
**Basic info**

| Distro (Name and version) | PHP Version | Valet version |
| ------------------------- | ----------- | ------------- |
| Linux Mint 21.1          | 7.4       | v2.3.0         |

- [x] I've checked the issue queue and could not find anything similar to my bug.
- [x] I'm on the latest version of valet-linux (`valet --version`): `v2.3.0`
- [x] I've run `valet fix` and `valet install` after updating and before submitting my issue/feature: `Command "fix" is not defined.`

**What is the problem?**
I get a 502 Bad Gateway. Looking in the `~/.valet/Log/nginx-error.log` I get `connect() to unix:/home/user/.valet/valet.sock`.
In my ~/.valet directory is only a `valet74.sock`.

**What was supposed to happen?**
Valet should create a `~/.valet/valet.sock` file.

**What actually happened?**
Valet only created a `~/.valet/valet74.sock` file.

**How to reproduce this?**
I don't exactly know.
I currently have set `valet use 7.4`. When running `valet use 8.1` a `~/.valet/valet81.sock` is created instead, but still no `valet.sock`.
I have used the `valet isolate 7.4` feature on multiple pages.

**What is the solution?**
My current workaround is to run `sudo ln -s ~/.valet/valet74.sock ~/.valet/valet.sock`

**Sources**
All sources related to the bug. If the bug uses external tools like PHP extensions it should at
least contain a link to the tool. Any other media which proves helpful can be included here.

**Comment by RCady** [comment]
Hey there! I was running into this as well and realized that the error was due to permissions on the `.valet` directory. For me, it was owned by `root:root`. Changing ownership to `myuser:myuser` recursively worked just fine in fixing it. I haven't had any issues with it so far.

The symlink is intended to be created upon `valet install` as the current user and not root. So it's necessary to ensure that your user can write to the directory. I'm not quite sure what caused my .valet directory to be owned by root though, so that could be something to look into.

So, in order to fix this bug, you should take the following steps:
1. Ensure your user has ownership of the `.valet` directory `sudo chown -R ~/.valet myuser:myuser`.
2. `valet install`

**Comment by RafaelKr** [comment]
Thanks @RCady, that actually worked. (You have swapped the `user:group` and path arguments to `chown`.)

But yes, I didn't set `~/.valet` to `root:root` manually, so this should be investigated.

**Comment by tricarte** [comment]
I had this problem too. I didn't realize that ~/.valet directory was owned by root and how that happened is still a mystery.

**Comment by lukastom** [comment]
I have this problem even when .valet permissions are recursively set to myuser:myuser. Only this workaround: `sudo ln -s ~/.valet/valet74.sock ~/.valet/valet.sock` works for me.

**Comment by abbasmashaddy72** [comment]
Still same issue persists I tried using older version but same issue, but recently I use old version I did not have any issue but not it is not working

@lukastom

**Comment by abbasmashaddy72** [comment]
I have installed V 2.0.22 it is working fine
