### ISSUE TITLE
use valet with wifi network from laptop as hotspot network

### ISSUE THREAD

**Issue by osman-mohamad** [cpriego/valet-linux#53]
hi, I know this not an issue with the code . but I did not know where to ask this question . so here I am

I want to develop application with laravel as api for mobile applications . I have laptop running ubuntu 16.04 with valet installed on it . by default valet domains can be accessed locally . or by share some random link . I want custom static domain name served from my ubuntu laptop by the android application I use .
how the two are connected . using ubuntu network manager i managed to make hotstop wifi network the mobile can use . the default ip address for the server when open the hotspot is 10.42.0.1 . i tried to change the ip in the /etc/networkMananger/dnsmasq.d/valet . but with no luck .

if any one use valet to develop api servers for mobile application . tell me about how to handle the static custom domain problem ?

thank you

**Comment by TheNodi** [comment]
Do you want to allow the mobile phone to connect to your laptop for testing using the same `.dev` domain?

In that case you need to allow the phone to resolve the domain to the network ip address. The fastest way to do it would be to setup the phone to use your laptop as a DNS server (when you connect to a network there should be "advanced network settings" which allows you to customize the primary and secondary DNS servers). You can then setup dnsmasq to map all `.dev` domains to your laptop ip address (`10.42.0.1`). This way both your laptop and any device connected to the hotspot can resolve the domains.

You might need to update your dnsmasq configs when you enable/disable the hotspot since the ip might change (or be removed when hotspot is off).

**Comment by osman-mohamad** [comment]
do you have step by step guide to do this ?

**Comment by TheNodi** [comment]
I just came up with the idea so unfortunately I don't.

You should change the ip in `/etc/NetworkManager/dnsmasq.d/valet` from `127.0.0.1` to `10.42.0.1`. I don't know if dnsmasq is available as a DNS server on the all network, you must try it and google it.
See: https://www.linux.com/learn/dnsmasq-easy-lan-name-services

For the phone, in android you just hold down the wi-fi network, choose "Edit Network" and fill the DNS1 and DNS2 fields with your laptop address. I don't know how to do it on i-phone but it should be something similar.
See:
- http://xslab.com/2013/08/how-to-change-dns-settings-on-android/
- http://www.iphonehacks.com/2014/08/change-dns-iphone-ipad.html

**Comment by cpriego** [comment]
@osman-mohamad just building up on what @TheNodi said, you could bind dnsmasq to address `0.0.0.0` for it to serve dns on your network. Also, not knowing how did you set up your laptop as a hotspot, you could add your laptop address as DNS nameservers in the DHCP server config (the one assigning the address `10.42.0.x`)

**Comment by TheNodi** [comment]
Closed for inactivity.
