### ISSUE TITLE
Google Chrome error ERR_ICANN_NAME_COLLISION on Ubuntu 17.04

### ISSUE THREAD

**Issue by arrakeen** [cpriego/valet-linux#55]
Everything worked well until today when I upgraded Ubuntu from 16.10 to 17.04.

I've tried the fixes you've provided on the wiki and in [this thread](https://github.com/cpriego/valet-linux/issues/7) but nothing seems to be working.
I'm still getting the "ERR_ICANN_NAME_COLLISION" error on Google Chrome.

The nameserver is set to `127.0.0.53` in the /etc/resolv.conf file.
The `/etc/NetworkManager/NetworkManager.conf` file's content is:

```
[main]
plugins=ifupdown,keyfile
dns=dnsmasq

[ifupdown]
managed=false
```
I've stopped the dnsmasq service and restarted the network manager and even reinstalled and upgraded valet to the latest version without success.

Any help would be greatly appreciated.

**Comment by tomicakorac** [comment]
@arrakeen the issue you're facing has actually nothing to do with the other thread you followed. I really don't know what made you think that these two issues are in any way related.

The error you're receiving is very well known and it occurs because .dev domain has become a registeed ICANN Top Level Domain. You can find tons of information about it on the internet. The work-arounds to solve this error:

1. Change your local domain from .dev to some other domain which isn't yet registered with ICANN, for example .local;
2. Use a different browser (Chromium, or any other really except Chrome)

You can also try to follow this thread:

http://www.pcappspot.com/fix-err-name-not-resolved/

It shows examples in Windows, but it should be analogous on Linux too.

**Comment by hakanersu** [comment]
I think #7 still not resolved yet and i guess your dnsmasq service not running so its try to resolve from ICANN.  Im getting same error when i stopped dnsmasq service.

I have fresh 17.04 installation, with dnsmasq service running i cant resolve any domain  when i stop service i can access websites as usual. There is a lot of threads about systemd-resolved and dnsmasq but i cant find any solutions yet.

Unfortunately you can set .dev domains in /etc/hosts file for temporary solution.

**Comment by arrakeen** [comment]
@tomicakorac actually I understood that .dev domains have become a registered top level domain before posting here but dnsmasq is supposed to override that, right ?
It didn't work with chromium and firefox and the error occured with another local domain (.local) too

@hakanersu thanks that's exactly what i've done, it works

**Comment by cpriego** [comment]
@arrakeen there seems to be an incompatibility. Whenever using dnsmasq in 17.04 everything stops working. Disabling systemd-resolved does not help either. I'm trying to figure this out but any help would be really appreciated.

**Comment by stephan-v** [comment]
Does not seem to be solved at all even though this is referenced with a commit.

I have added:
```
address=/.dev/127.0.0.1
```

To `/etc/dnsmasq.conf`, Works perfectly fine now.

**Comment by dakira** [comment]
I opened a new issue [here](https://github.com/cpriego/valet-linux/issues/71) but I'm actually quite sure it's very related to this one.

**Comment by stephan-v** [comment]
@dakira probably. I did a fresh ubuntu 16.04 installation a couple of days ago. By doing a second clean install of valet-linux and adding the rule to the `dnsmasq.conf` everything works again.

**Comment by dakira** [comment]
@stephan-v as the title of this (any my bug) states: This occurs in Ubuntu 17.04 and is related to its DNS configuration. Problems in 16.04 are unrelated to this.
