### ISSUE TITLE
Valet is not automatically starting after a system reboot.

### ISSUE THREAD

**Issue by lxsymington** [cpriego/valet-linux#66]
First off  @cpriego et al thanks for porting valet! It's making switching between mac and linux much simpler!

I may have misinterpreted the docs but my understanding was that valet should automatically start on system boot, this is not happening for me, I have to `valet restart` each time I boot, but after that it works exactly as expected.

OS: Ubuntu 17.04
PHP: 7.0.15
NetworkManager: 1.4.4

**Comment by cpriego** [comment]
Thanks @lxsymington!

First, let me describe how Valet works in Linux.

Valet installs (and enables) various services to "serve" PHP and static files. Valet does not automatically start as it has nothing to start, that's the job of the installed services and OS. When running `valet restart` we are just restarting those services.

Now, something must have gone wrong during installation for the services are not being started.

We need to do some troubleshooting so I'll need your help running some commands and sharing the output:
```
systemctl is-enabled {nginx,php7.0-fpm}
```

**Comment by lxsymington** [comment]
![screenshot from 2017-05-07 11-34-44](https://cloud.githubusercontent.com/assets/15095115/25780032/3f4c3f64-3319-11e7-89be-b92cc499dd19.png)

**Comment by TheNodi** [comment]
It looks like nginx and php couldn't access the socket and log files when they initially tried to start.

I'm not sure what can be causing it, the first thing that comes into my mind is encryption, is the home folder encrypted? Those services tried to start up before you logged into the machine and at that point the home folder isn't yet mounted (it's mounted on login and unmounted on logout).

**Comment by lxsymington** [comment]
![screenshot from 2017-05-07 22-56-52](https://cloud.githubusercontent.com/assets/15095115/25785454/938321ba-3378-11e7-87e7-8665dfd19eae.png)

I didn't think I had Apache installed but checked anyway, and I don't. From the output attached it does look like my home directory is encrypted, so @TheNodi your theory seems like the current frontrunner!

**Comment by TheNodi** [comment]
You can try to login as root user (or any other user capable of starting nginx/php-fpm services) and see if the home folder is mounted or not, but I took those information from the Ubuntu wiki so they sould be correct. If that's the source of the problem there isn't much we can do, other than moving sockets and logs file in another directory, but it would require more work than it's worth doing.

Honestly, since typing `valet restart` when needed isn't hard, I would stick with the encrypted partition and leave it as is. To avoid errors just disable nginx and php-fpm on startup.

**Comment by lxsymington** [comment]
Fair, thanks for the help!
