### ISSUE TITLE
Feature Request: implement valet plus feature set

### ISSUE THREAD

**Issue by wowcut** [cpriego/valet-linux#91]
HI, it is very nice to have valet on ubuntu too,but it would be even nicer to have the features of [valet plus](https://github.com/weprovide/valet-plus) implemented here. I am sure you like it too :) 

Thanks and have a nice day!

**Comment by TheNodi** [comment]
I read the Valet Plus documentation for a couple of minutes, unfortunately I cannot try it out (I don't have a Mac). 

I usually prefer to follow a microservice-like approach to this kind of software as well, "Do as fee as possible, do it well", so I am a bit skeptical about those feature build-in into valet.
Although, I'm not the Owner of this project, so last word goes to @cpriego 

 - PHP version switch: This is a bit tricky, every OS can handle PHP differently. On fedora you need a remirepo to install multiple php versions at the same time (to then switch a symlink around). On ubuntu this is different, and it goes on this way. 
- Xdebug (on/off mode): This is quite easy, you just toggle a setting and restart PHP. It can be implemented.
- PHP extensions (mcrypt, intl, opcache, apcu): I always need mcrypt and intl. I would not want opcache on my dev machine, and I don't use apcu. My point is: everyone has different needs when it come to PHP extensions, I don't feel like installing too many of them by default. Some might be good (mcrypt, intl, posix, ...).
- Optimized PHP configuration using opcache: As mentioned above, I don't like (read hate) opcache on a dev machine, it gives you more problem than solutions. 
- MySQL (with optimized configuration): There might be people who don't use MySQL, so I would not install it by default, but the management commands (`valet db ...`) are really nice. I personally setup a `phpmyadmin` valet site to manage MySQL, but this can be a really nice solution. 
- Redis: I don't have pros or cons to this as a Laravel developer, might be nice to hear someone else opinion to see if they need this.
- Elasticsearch (optional): This is not a light stack to install, so it must remain an optional thing. 

Honestly I would leave most of the installation as optional, maybe with a prompt on the first install. 

This are just my opinions on the feature, I would love to hear other's opinions and even change mine if needed. Since there're efforts to put in this features, discussions are welcome.

**Comment by cpriego** [comment]
@wowcut I totally agree with @TheNodi on this, Valet should remain as simple as possible and Valet Plus does a LOT of things. That being said, some features are worth integrating while others are easily done through the distros' own tools (read Package Managers)

|     |     |
|-----|-----|
| PHP version switch  | Linux has a ton of ways of doing this, the simplest one being docker. Homestead has this already baked in.  |
| Xdebug switch | Easily doable. **Will add the toggle feature.**  |
| Mailhog | Easily doable. **Could be added but would require the mailhog binary**  |
| PHP Extensions | Too complex as each distro packs extensions in very varying ways |
| OPCache | Caching is oriented towards **production** environments. Valet is oriented to dev environments. |
| Redis | Could be **optional** |
| Databases | I don't want to bloat the user's computer with software they won't use.  May add **optional** installer |
| Elasticsearch | This depends on the JRE. Not even Homestead includes this and Valet would divert from its **light environment** focus. |

Apart from the PHP versions and extensions feature (which are really tricky to implement) and `db` commands the rest of the features could be added by extending the `valet install` command and adding other commands (like `valet xdebug`).

| Command  | Description |
|-----|-----|
| `valet install <package>` | This would allow you to install  a specific "plus" package (redis, elasticsearch or any RDBMS) |
| `valet install plus` | This would allow you to install the "plus" packages (redis, elasticsearch, mariadb) |
| `valet xdebug <on/off>` | This would toggle xdebug |
| `valet mailhog <on/off>` | This would toggle mailhog |

**Comment by codepuncher** [comment]
Has there been any further progress with this since? Would like to see if there's a possibility of working on a PR (at least for xDebug).

**Comment by swastik009** [comment]
Any luck on valet xdebug <on/off> command ??
