### ISSUE TITLE
Chrome forcing *.dev-tld domains to HTTPS

### ISSUE THREAD

**Issue by nickurt** [cpriego/valet-linux#98]
In the [upcoming version of Google Chrome](https://ma.ttias.be/chrome-force-dev-domains-https-via-preloaded-hsts/), it will be forcing *.dev-tlds to HTTPS since *.dev is a valid gTLD these days.

Is it an idea to change the default tld in valet-linux to [*.localhost](https://tools.ietf.org/html/draft-west-let-localhost-be-localhost-06) since that looks a better solution for now ..

**Comment by TheNodi** [comment]
Such beautiful news on a Monday morning. 

Given the list of [reserver top-level domains](https://en.wikipedia.org/wiki/Top-level_domain#Reserved_domains), I would propose the use of [`.test`](https://en.wikipedia.org/wiki/.test) instead of `.localhost` mainly because is shorter to type and the localhost domain is still a draft.

In an hypothetical future where that draft gets accepted and all `*.localhost` domains will be automatically directed to `127.0.0.1`, valet's work would be way simpler.

**Comment by nickurt** [comment]
Ok, agree TheNodi, if you want I can make a pull-request for this later today.

**Comment by TheNodi** [comment]
It would be highly appreciated, thank you!

**Comment by cpriego** [comment]
@nickurt thanks a lot! this has been merged to master

**Comment by CydeWeys** [comment]
Thank you!
